#!/usr/bin/php
<?php

require 'legacy/MintCLI/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new MintHCM\MintCLI\Commands\Install());
$application->add(new MintHCM\MintCLI\Commands\DemoDataDumpCommand());
$application->add(new MintHCM\MintCLI\Commands\DemoDataInstallCommand());
$application->add(new MintHCM\MintCLI\Commands\ElasticSearchReindex());
$application->add(new MintHCM\MintCLI\Commands\ElasticSearchReindexModule());

$application->run();
