<?php


/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2023 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN Candidates
 */
require_once 'include/SugarObjects/templates/person/Person.php';

class Candidates_sugar extends Person {

   public $new_schema = true;
   public $module_dir = 'Candidates';
   public $object_name = 'Candidates';
   public $table_name = 'candidates';
   public $importable = true;
   public $assigned_user_id;
   public $assigned_user_name;
   public $assigned_user_link;
   public $id;
   public $name;
   public $date_entered;
   public $date_modified;
   public $modified_user_id;
   public $modified_by_name;
   public $created_by;
   public $created_by_name;
   public $doc_owner;
   public $user_favorites;
   public $description;
   public $deleted;
   public $created_by_link;
   public $modified_user_link;
   public $activities;
   public $following;
   public $following_link;
   public $my_favorite;
   public $favorite_link;
   public $salutation;
   public $first_name;
   public $last_name;
   public $full_name;
   public $title;
   public $facebook;
   public $twitter;
   public $googleplus;
   public $department;
   public $do_not_call;
   public $phone_mobile;
   public $phone_work;
   public $phone_other;
   public $phone_fax;
   public $primary_address_street;
   public $primary_address_street_2;
   public $primary_address_street_3;
   public $primary_address_city;
   public $primary_address_state;
   public $primary_address_postalcode;
   public $primary_address_country;
   public $alt_address_street;
   public $alt_address_street_2;
   public $alt_address_street_3;
   public $alt_address_city;
   public $alt_address_state;
   public $alt_address_postalcode;
   public $alt_address_country;
   public $assistant;
   public $assistant_phone;
   public $picture;
   public $email;
   public $email1;
   public $email2;
   public $invalid_email;
   public $email_opt_out;
   public $email_addresses_primary;
   public $email_addresses;
   public $email_addresses_non_primary;

   public function bean_implements($interface) {
      if ( $interface == 'ACL' ) {
         return true;
      }
      return false;
   }

}
