<?php
$config = [
    'blacklist_tables' => [
        "accounts_bugs",
        "accounts_cases",
        "accounts_contacts",
        "accounts_opportunities",
        "alerts",
        "allocations_audit",
        "am_projecttemplates_audit",
        "am_tasktemplates_audit",
        "aod_index",
        "aod_index_audit",
        "aod_indexevent",
        "aod_indexevent_audit",
        "aok_knowledge_base_categories_audit",
        "aok_knowledgebase_audit",
        "aor_reports_audit",
        "aos_contracts_documents",
        "aos_pdf_templates_audit",
        "aos_quotes_aos_invoices_c",
        "aos_quotes_os_contracts_c",
        "aos_quotes_project_c",
        "aow_workflow_audit",
        "applications_audit",
        "appraisalitems_audit",
        "appraisals_audit",
        "attitudes_audit",
        "benefits_audit",
        "calls_audit",
        "calls_reschedule_audit",
        "campaigns_audit",
        "candidates_audit",
        "candidatures_audit",
        "careerpaths_audit",
        "cases_bugs",
        "certificates_audit",
        "competencies_audit",
        "competencyratings_audit",
        "conclusions_audit",
        "config",
        "contacts_bugs",
        "contacts_cases",
        "contacts_users",
        "contracts_audit",
        "costs_audit",
        "cron_remove_documents",
        "custom_fields",
        "dashboardmanager_audit",
        "delegations_audit",
        "delegationslocale_audit",
        "dictionaries_audit",
        "eapm",
        "email_addresses_audit",
        "employeecertificates_audit",
        "employeeroles_audit",
        "exitinterviews_audit",
        "fields_meta_data",
        "files_audit",
        "fp_event_locations_audit",
        "fp_events_audit",
        "goals_audit",
        "ideas_audit",
        "improvements_audit",
        "jjwg_maps_jjwg_areas_c",
        "jjwg_maps_jjwg_markers_c",
        "job_queue",
        "knowledge_audit",
        "ktemplates_audit",
        "last_next_contact_queue",
        "meetings_audit",
        "news_audit",
        "oauth2clients",
        "oauth2tokens",
        "oauth_consumer",
        "oauth_nonce",
        "oauth_tokens",
        "offboardings_audit",
        "offboardingtemplates_audit",
        "onboardingoffboardingelements_audit",
        "onboardings_audit",
        "onboardingtemplates_audit",
        "opportunities_contacts",
        "outbound_email",
        "outbound_email_audit",
        "periodsofemployment_audit",
        "positions_audit",
        "problems_audit",
        "project_contacts_1_c",
        "project_task_audit",
        "projects_accounts",
        "projects_contacts",
        "projects_opportunities",
        "projects_products",
        "recruitments_audit",
        "relationships",
        "requests_audit",
        "reservations_audit",
        "reservationscalendar_audit",
        "resources_audit",
        "responsibilities_audit",
        "responsibilityactivities_audit",
        "rooms_audit",
        "salaryranges_audit",
        "saved_search",
        "schedulereports_audit",
        "schedulereportslogs",
        "schedulereportslogs_audit",
        "securitygroups_audit",
        "skills_audit",
        "spenttime_audit",
        "surveyquestionoptions_audit",
        "surveyquestionresponses_audit",
        "surveyquestions_audit",
        "surveyresponses_audit",
        "surveys_audit",
        "tasks_audit",
        "termsofemployment_audit",
        "tracker",
        "trainings_audit",
        "transportations_audit",
        "upgrade_history",
        "users_audit",
        "usersnews_audit",
        "view_tools_queue",
        "workplaces_audit",
        "workschedules_audit",
    ],
    'files' => [
        [
            'table' => 'users',
            'column' => 'id',
            'postfix' => '_photo',
        ],
        [
            'table' => 'rooms',
            'column' => 'id',
            'postfix' => '_room_plan',
        ],
        [
            'table' => 'notes',
            'column' => 'id',
            'postfix' => '',
        ],
        [
            'table' => 'document_revisions',
            'column' => 'id',
            'postfix' => '',
        ],
        [
            'table' => 'document_revisions',
            'column' => 'id',
            'postfix' => '',
        ],
        [
            'table' => 'files',
            'column' => 'id',
            'postfix' => '',
        ],
    ]
];