<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="calls", indexes={
 * @ORM\Index(name="callspk", columns={"id"}), 
 * @ORM\Index(name="idx_call_name", columns={"name"}), 
 * @ORM\Index(name="idx_status", columns={"status"}), 
 * @ORM\Index(name="idx_calls_date_start", columns={"date_start"}), 
 * @ORM\Index(name="idx_calls_date_end", columns={"date_end"}), 
 * @ORM\Index(name="idx_calls_duration_minutes", columns={"duration_minutes"}), 
 * @ORM\Index(name="idx_calls_duration_hours", columns={"duration_hours"}), 
 * @ORM\Index(name="idx_calls_par_del", columns={"parent_id", "parent_type", "deleted"}), 
 * @ORM\Index(name="idx_calls_assigned_del", columns={"deleted", "assigned_user_id"})})
 * @property mixed $id
 * @property mixed $name
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $date_indexed
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $description
 * @property mixed $deleted
 * @property mixed $assigned_user_id
 * @property mixed $duration_hours
 * @property mixed $duration_minutes
 * @property mixed $date_start
 * @property mixed $date_end
 * @property mixed $parent_type
 * @property mixed $status
 * @property mixed $direction
 * @property mixed $parent_id
 * @property mixed $reminder_time
 * @property mixed $email_reminder_time
 * @property mixed $email_reminder_sent
 * @property mixed $outlook_id
 * @property mixed $repeat_type
 * @property mixed $repeat_interval
 * @property mixed $repeat_dow
 * @property mixed $repeat_until
 * @property mixed $repeat_count
 * @property mixed $repeat_parent_id
 * @property mixed $recurring_source
 */
// Auto-generated SectionRepository section end
class Calls extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="text")
     */
    protected $description;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $assigned_user_id;

    /**
     * @ORM\Column(type="integer", length="2")
     */
    protected $duration_hours;

    /**
     * @ORM\Column(type="integer", length="2")
     */
    protected $duration_minutes;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_start;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_end;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $parent_type;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $status;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $direction;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $parent_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $reminder_time;

    /**
     * @ORM\Column(type="integer")
     */
    protected $email_reminder_time;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $email_reminder_sent;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $outlook_id;

    /**
     * @ORM\Column(type="string", length="36")
     */
    protected $repeat_type;

    /**
     * @ORM\Column(type="integer", length="3")
     */
    protected $repeat_interval;

    /**
     * @ORM\Column(type="string", length="7")
     */
    protected $repeat_dow;

    /**
     * @ORM\Column(type="date")
     */
    protected $repeat_until;

    /**
     * @ORM\Column(type="integer", length="7")
     */
    protected $repeat_count;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $repeat_parent_id;

    /**
     * @ORM\Column(type="string", length="36")
     */
    protected $recurring_source;

    /**
     * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="calls")
     */
    protected $modified_user_link;

    /**
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="calls")
     */
    protected $created_by_link;

    /**
     * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="calls")
     */
    protected $assigned_user_link;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="calls")
     */
    protected Collection $notes;

    /**
     * @ORM\OneToMany(targetEntity=Calls_Reschedule::class, mappedBy="calls_reschedule")
     */
    protected Collection $calls_reschedule;

    /**
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Project::class, inversedBy="calls")
     */
    protected $project;

    /**
     * @ORM\JoinTable(name="calls_users")
     * @ORM\ManyToMany(targetEntity=Users::class, mappedBy="calls")
     */
    protected Collection $users;

    /**
     * @ORM\JoinTable(name="calls_candidates")
     * @ORM\ManyToMany(targetEntity=Candidates::class, mappedBy="calls")
     */
    protected Collection $candidates;

    /**
     * @ORM\OneToMany(targetEntity=Reservations::class, mappedBy="reservations")
     */
    protected Collection $reservations;

    /**
     * @ORM\JoinTable(name="calls_resources")
     * @ORM\ManyToMany(targetEntity=Resources::class, mappedBy="calls")
     */
    protected Collection $resources;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->SecurityGroups = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->calls_reschedule = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->candidates = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->resources = new ArrayCollection();
    }

    // Auto-generated SectionMethods section end
}
