<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="campaigns", indexes={
 * @ORM\Index(name="campaignspk", columns={"id"}), 
 * @ORM\Index(name="camp_auto_tracker_key", columns={"tracker_key"}), 
 * @ORM\Index(name="idx_campaign_name", columns={"name"}), 
 * @ORM\Index(name="idx_survey_id", columns={"survey_id"})})
 * @property mixed $id
 * @property mixed $name
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $date_indexed
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $deleted
 * @property mixed $assigned_user_id
 * @property mixed $tracker_key
 * @property mixed $tracker_count
 * @property mixed $refer_url
 * @property mixed $tracker_text
 * @property mixed $start_date
 * @property mixed $end_date
 * @property mixed $status
 * @property mixed $impressions
 * @property mixed $currency_id
 * @property mixed $budget
 * @property mixed $expected_cost
 * @property mixed $actual_cost
 * @property mixed $expected_revenue
 * @property mixed $campaign_type
 * @property mixed $objective
 * @property mixed $content
 * @property mixed $frequency
 * @property mixed $survey_id
 */
// Auto-generated SectionRepository section end
class Campaigns extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $assigned_user_id;

    /**
     * @ORM\Column(type="integer", length="11")
     */
    protected $tracker_key;

    /**
     * @ORM\Column(type="integer", length="11")
     */
    protected $tracker_count;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $refer_url;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $tracker_text;

    /**
     * @ORM\Column(type="date")
     */
    protected $start_date;

    /**
     * @ORM\Column(type="date")
     */
    protected $end_date;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $status;

    /**
     * @ORM\Column(type="integer")
     */
    protected $impressions;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $currency_id;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $budget;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $expected_cost;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $actual_cost;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $expected_revenue;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $campaign_type;

    /**
     * @ORM\Column(type="text")
     */
    protected $objective;

    /**
     * @ORM\Column(type="text")
     */
    protected $content;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $frequency;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $survey_id;

    /**
     * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="campaigns")
     */
    protected $modified_user_link;

    /**
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="campaigns")
     */
    protected $created_by_link;

    /**
     * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="campaigns")
     */
    protected $assigned_user_link;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="campaigns")
     */
    protected Collection $notes;

    /**
     * @ORM\OneToMany(targetEntity=EmailMarketing::class, mappedBy="email_marketing")
     */
    protected Collection $emailmarketing;

    /**
     * @ORM\OneToMany(targetEntity=EmailMan::class, mappedBy="emailman")
     */
    protected Collection $queueitems;

    /**
     * @ORM\OneToMany(targetEntity=CampaignLog::class, mappedBy="campaign")
     */
    protected Collection $log_entries;

    /**
     * @ORM\OneToMany(targetEntity=SurveyResponses::class, mappedBy="campaign")
     */
    protected Collection $surveyresponses_campaigns;

    /**
     * @ORM\JoinTable(name="prospect_list_campaigns", joinColumns={@ORM\JoinColumn(name="campaign_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="prospect_list_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=ProspectLists::class, inversedBy="campaigns")
     */
    protected Collection $prospectlists;

    /**
     * @ORM\OneToMany(targetEntity=CampaignTrackers::class, mappedBy="campaign")
     */
    protected Collection $tracked_urls;

    /**
     * @ORM\JoinColumn(name="survey_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Surveys::class, inversedBy="campaigns")
     */
    protected $survey;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->SecurityGroups = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->emailmarketing = new ArrayCollection();
        $this->queueitems = new ArrayCollection();
        $this->log_entries = new ArrayCollection();
        $this->surveyresponses_campaigns = new ArrayCollection();
        $this->prospectlists = new ArrayCollection();
        $this->tracked_urls = new ArrayCollection();
    }

    // Auto-generated SectionMethods section end
}
