<?php
// Generated by the Entity Creator: 2025-06-09 11:19:24

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity
 * @ORM\Table(name="campaign_log", indexes={
 *   @ORM\Index(name="campaign_log_pk", columns={"id"}), 
 *   @ORM\Index(name="idx_camp_tracker", columns={"target_tracker_key"}), 
 *   @ORM\Index(name="idx_camp_campaign_id", columns={"campaign_id"}), 
 *   @ORM\Index(name="idx_camp_more_info", columns={"more_information"}), 
 *   @ORM\Index(name="idx_target_id", columns={"target_id"}), 
 *   @ORM\Index(name="idx_target_id_deleted", columns={"target_id", "deleted"})})
 */
class CampaignLog
{
    /**
        * @ORM\Id
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $campaign_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $target_tracker_key;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $target_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $target_type;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $activity_type;

    /**
            * @ORM\Column(type="datetime")
            */
    public $activity_date;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $related_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $related_type;

    /**
            * @ORM\Column(type="boolean")
            */
    public $archived;

    /**
            * @ORM\Column(type="integer")
            */
    public $hits;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $list_id;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $more_information;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $marketing_id;

    /**
        * @ORM\OneToMany(targetEntity=Users::class, mappedBy="campaign_log")
        */
    public Collection $targeted_user;

    /**
        * @ORM\OneToMany(targetEntity=Emails::class, mappedBy="campaign_log")
        */
    public Collection $sent_email;

    /**
        * @ORM\JoinColumn(name="campaign_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Campaigns::class, inversedBy="campaign_log")
        */
    public $campaign;


public function __construct()
{
        $this->targeted_user = new ArrayCollection();
        $this->sent_email = new ArrayCollection();
    }
}