<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="candidates", indexes={
 * @ORM\Index(name="candidatespk", columns={"id"})})
 * @property mixed $id
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $date_indexed
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $description
 * @property mixed $deleted
 * @property mixed $assigned_user_id
 * @property mixed $salutation
 * @property mixed $first_name
 * @property mixed $last_name
 * @property mixed $title
 * @property mixed $photo
 * @property mixed $department
 * @property mixed $do_not_call
 * @property mixed $phone_home
 * @property mixed $phone_mobile
 * @property mixed $phone_work
 * @property mixed $phone_other
 * @property mixed $phone_fax
 * @property mixed $email1
 * @property mixed $lawful_basis
 * @property mixed $date_reviewed
 * @property mixed $lawful_basis_source
 * @property mixed $primary_address_street
 * @property mixed $primary_address_city
 * @property mixed $primary_address_state
 * @property mixed $primary_address_postalcode
 * @property mixed $primary_address_country
 * @property mixed $alt_address_street
 * @property mixed $alt_address_city
 * @property mixed $alt_address_state
 * @property mixed $alt_address_postalcode
 * @property mixed $alt_address_country
 * @property mixed $assistant
 * @property mixed $assistant_phone
 * @property mixed $recr_contact_agree
 * @property mixed $collaboration
 * @property mixed $relocation
 * @property mixed $birthdate
 * @property mixed $github
 * @property mixed $linkedin
 * @property mixed $x_service
 * @property mixed $facebook
 * @property mixed $potential
 * @property mixed $last_time_contact
 * @property mixed $date_planned_contact
 */
// Auto-generated SectionRepository section end
class Candidates extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="text")
     */
    protected $description;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $assigned_user_id;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $salutation;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $first_name;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $last_name;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $title;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $photo;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $department;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $do_not_call;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $phone_home;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $phone_mobile;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $phone_work;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $phone_other;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $phone_fax;

    /**
     */
    protected $email1;

    /**
     * @ORM\Column(type="multienum", length="100")
     */
    protected $lawful_basis;

    /**
     * @ORM\Column(type="date")
     */
    protected $date_reviewed;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $lawful_basis_source;

    /**
     * @ORM\Column(type="string", length="150")
     */
    protected $primary_address_street;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $primary_address_city;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $primary_address_state;

    /**
     * @ORM\Column(type="string", length="20")
     */
    protected $primary_address_postalcode;

    /**
     * @ORM\Column(type="string")
     */
    protected $primary_address_country;

    /**
     * @ORM\Column(type="string", length="150")
     */
    protected $alt_address_street;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $alt_address_city;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $alt_address_state;

    /**
     * @ORM\Column(type="string", length="20")
     */
    protected $alt_address_postalcode;

    /**
     * @ORM\Column(type="string")
     */
    protected $alt_address_country;

    /**
     * @ORM\Column(type="string", length="75")
     */
    protected $assistant;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $assistant_phone;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $recr_contact_agree;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $collaboration;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $relocation;

    /**
     * @ORM\Column(type="date")
     */
    protected $birthdate;

    /**
     * @ORM\Column(type="string")
     */
    protected $github;

    /**
     * @ORM\Column(type="string")
     */
    protected $linkedin;

    /**
     * @ORM\Column(type="string")
     */
    protected $x_service;

    /**
     * @ORM\Column(type="string")
     */
    protected $facebook;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $potential;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $last_time_contact;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_planned_contact;

    /**
     * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidates")
     */
    protected $modified_user_link;

    /**
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidates")
     */
    protected $created_by_link;

    /**
     * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidates")
     */
    protected $assigned_user_link;

    /**
     * @ORM\JoinTable(name="email_addr_bean_rel", joinColumns={@ORM\JoinColumn(name="bean_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="email_address_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=EmailAddresses::class, inversedBy="email_addresses")
     */
    protected Collection $email_addresses;

    /**
     * @ORM\JoinTable(name="email_addr_bean_rel", joinColumns={@ORM\JoinColumn(name="bean_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="email_address_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=EmailAddresses::class, inversedBy="email_addresses")
     */
    protected Collection $email_addresses_primary;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\OneToMany(targetEntity=Candidatures::class, mappedBy="candidatures")
     */
    protected Collection $candidatures;

    /**
     * @ORM\JoinTable(name="emails_beans")
     * @ORM\ManyToMany(targetEntity=Emails::class, mappedBy="candidates")
     */
    protected Collection $emails;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="notes")
     */
    protected Collection $notes;

    /**
     * @ORM\OneToMany(targetEntity=Tasks::class, mappedBy="tasks")
     */
    protected Collection $tasks;

    /**
     * @ORM\JoinTable(name="documents_candidates", joinColumns={@ORM\JoinColumn(name="candidate_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="document_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Documents::class, inversedBy="candidates")
     */
    protected Collection $documents;

    /**
     * @ORM\JoinTable(name="calls_candidates", joinColumns={@ORM\JoinColumn(name="candidate_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="call_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Calls::class, inversedBy="candidates")
     */
    protected Collection $calls;

    /**
     * @ORM\JoinTable(name="meetings_candidates", joinColumns={@ORM\JoinColumn(name="candidate_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Meetings::class, inversedBy="candidates")
     */
    protected Collection $meetings;

    /**
     * @ORM\OneToMany(targetEntity=EmployeeCertificates::class, mappedBy="candidate")
     */
    protected Collection $employeecertificates;

    /**
     * @ORM\JoinTable(name="candidates_employees")
     * @ORM\ManyToMany(targetEntity=Users::class, mappedBy="candidates")
     */
    protected Collection $employee;

    /**
     * @ORM\OneToMany(targetEntity=Files::class, mappedBy="candidate")
     */
    protected Collection $files;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->email_addresses = new ArrayCollection();
        $this->email_addresses_primary = new ArrayCollection();
        $this->SecurityGroups = new ArrayCollection();
        $this->candidatures = new ArrayCollection();
        $this->emails = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->calls = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->employeecertificates = new ArrayCollection();
        $this->employee = new ArrayCollection();
        $this->files = new ArrayCollection();
    }

        public function getEmail1(): string
        {
            $conn = $this->getEntityManager()->getConnection();

            $sql = '
                SELECT ea.email_address
                FROM email_addresses ea
                INNER JOIN email_addr_bean_rel eabr
                    ON eabr.email_address_id = ea.id
                WHERE eabr.bean_id = :bean_id
                AND eabr.bean_module = :bean_module
                AND eabr.primary_address = :primary_address
                AND eabr.deleted = :deleted
                LIMIT 1
            ';

            $module_name = $this->getModuleName();
            if (in_array($module_name, ['Employees'])) {
                $module_name = 'Users';
            }

            $stmt = $conn->prepare($sql);
            $result = $stmt->executeQuery([
                'bean_id' => $this->id,
                'bean_module' => $module_name,
                'primary_address' => 1,
                'deleted' => 0,
            ]);

            return $result->fetchOne() ?: '';
}

public function getSerialized(bool $json = false): array|string
{
    $data = parent::getSerialized($json);
    $data['email1'] = $this->getEmail1();
    return $data;
}
    // Auto-generated SectionMethods section end
}
