<?php
// Generated by the Entity Creator: 2025-06-09 11:19:24

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity
 * @ORM\Table(name="candidates", indexes={
 *   @ORM\Index(name="candidatespk", columns={"id"})})
 */
class Candidates
{
    /**
        * @ORM\Id
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_entered;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_indexed;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $modified_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $created_by;

    /**
            * @ORM\Column(type="text")
            */
    public $description;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $assigned_user_id;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $salutation;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $first_name;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $last_name;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $title;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $photo;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $department;

    /**
            * @ORM\Column(type="boolean")
            */
    public $do_not_call;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $phone_home;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $phone_mobile;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $phone_work;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $phone_other;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $phone_fax;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $lawful_basis;

    /**
            * @ORM\Column(type="date")
            */
    public $date_reviewed;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $lawful_basis_source;

    /**
            * @ORM\Column(type="string", length="150")
            */
    public $primary_address_street;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $primary_address_city;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $primary_address_state;

    /**
            * @ORM\Column(type="string", length="20")
            */
    public $primary_address_postalcode;

    /**
            * @ORM\Column(type="string")
            */
    public $primary_address_country;

    /**
            * @ORM\Column(type="string", length="150")
            */
    public $alt_address_street;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $alt_address_city;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $alt_address_state;

    /**
            * @ORM\Column(type="string", length="20")
            */
    public $alt_address_postalcode;

    /**
            * @ORM\Column(type="string")
            */
    public $alt_address_country;

    /**
            * @ORM\Column(type="string", length="75")
            */
    public $assistant;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $assistant_phone;

    /**
            * @ORM\Column(type="boolean")
            */
    public $recr_contact_agree;

    /**
            * @ORM\Column(type="boolean")
            */
    public $collaboration;

    /**
            * @ORM\Column(type="boolean")
            */
    public $relocation;

    /**
            * @ORM\Column(type="date")
            */
    public $birthdate;

    /**
            * @ORM\Column(type="string")
            */
    public $github;

    /**
            * @ORM\Column(type="string")
            */
    public $linkedin;

    /**
            * @ORM\Column(type="string")
            */
    public $skype;

    /**
            * @ORM\Column(type="string")
            */
    public $facebook;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $potential;

    /**
            * @ORM\Column(type="datetime")
            */
    public $last_time_contact;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_planned_contact;

    /**
        * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidates")
        */
    public $modified_user_link;

    /**
        * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidates")
        */
    public $created_by_link;

    /**
        * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidates")
        */
    public $assigned_user_link;

    /**
        * @ORM\JoinTable(name="email_addr_bean_rel")
        * @ORM\ManyToMany(targetEntity=EmailAddresses::class, mappedBy="candidates")
        */
    public Collection $email_addresses;

    /**
        * @ORM\JoinTable(name="email_addr_bean_rel")
        * @ORM\ManyToMany(targetEntity=EmailAddresses::class, mappedBy="candidates")
        */
    public Collection $email_addresses_primary;

    /**
        * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
        */
    public Collection $SecurityGroups;

    /**
        * @ORM\OneToMany(targetEntity=Candidatures::class, mappedBy="candidates")
        */
    public Collection $candidatures;

    /**
        * @ORM\JoinTable(name="emails_beans")
        * @ORM\ManyToMany(targetEntity=Emails::class, mappedBy="candidates")
        */
    public Collection $emails;

    /**
        * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="candidates")
        */
    public Collection $notes;

    /**
        * @ORM\OneToMany(targetEntity=Tasks::class, mappedBy="candidates")
        */
    public Collection $tasks;

    /**
        * @ORM\JoinTable(name="documents_candidates", joinColumns={@ORM\JoinColumn(name="candidate_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="document_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Documents::class, inversedBy="candidates")
        */
    public Collection $documents;

    /**
        * @ORM\JoinTable(name="calls_candidates", joinColumns={@ORM\JoinColumn(name="candidate_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="call_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Calls::class, inversedBy="candidates")
        */
    public Collection $calls;

    /**
        * @ORM\JoinTable(name="meetings_candidates", joinColumns={@ORM\JoinColumn(name="candidate_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Meetings::class, inversedBy="candidates")
        */
    public Collection $meetings;

    /**
        * @ORM\OneToMany(targetEntity=EmployeeCertificates::class, mappedBy="candidates")
        */
    public Collection $employeecertificates;

    /**
        * @ORM\JoinTable(name="candidates_employees")
        * @ORM\ManyToMany(targetEntity=Users::class, mappedBy="candidates")
        */
    public Collection $employee;

    /**
        * @ORM\OneToMany(targetEntity=Files::class, mappedBy="candidates")
        */
    public Collection $files;


public function __construct()
{
        $this->email_addresses = new ArrayCollection();
        $this->email_addresses_primary = new ArrayCollection();
        $this->SecurityGroups = new ArrayCollection();
        $this->candidatures = new ArrayCollection();
        $this->emails = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->calls = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->employeecertificates = new ArrayCollection();
        $this->employee = new ArrayCollection();
        $this->files = new ArrayCollection();
    }
}