<?php
// Generated by the Entity Creator: 2025-06-09 11:19:24

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity
 * @ORM\Table(name="candidatures", indexes={
 *   @ORM\Index(name="candidaturespk", columns={"id"})})
 */
class Candidatures
{
    /**
        * @ORM\Id
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $name;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_entered;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_indexed;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $modified_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $created_by;

    /**
            * @ORM\Column(type="text")
            */
    public $description;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $assigned_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $employee_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $currency_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $reason_for_rejection;

    /**
            * @ORM\Column(type="decimal")
            */
    public $dg_amount;

    /**
            * @ORM\Column(type="decimal")
            */
    public $dg_amount_usdollar;

    /**
            * @ORM\Column(type="decimal")
            */
    public $gross_amount;

    /**
            * @ORM\Column(type="decimal")
            */
    public $gross_amount_usdollar;

    /**
            * @ORM\Column(type="decimal")
            */
    public $net_amount;

    /**
            * @ORM\Column(type="decimal")
            */
    public $net_amount_usdollar;

    /**
            * @ORM\Column(type="text")
            */
    public $notice;

    /**
            * @ORM\Column(type="text")
            */
    public $notice_final_expectations;

    /**
            * @ORM\Column(type="decimal")
            */
    public $salary_net;

    /**
            * @ORM\Column(type="decimal")
            */
    public $salary_net_usdollar;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $scoring;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $source;

    /**
            * @ORM\Column(type="date")
            */
    public $start_date;

    /**
            * @ORM\Column(type="date")
            */
    public $work_start;

    /**
            * @ORM\Column(type="date")
            */
    public $training_date;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $status;

    /**
            * @ORM\Column(type="text")
            */
    public $status_information;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $task_grade;

    /**
            * @ORM\Column(type="boolean")
            */
    public $to_decision;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $final_employment_form;

    /**
            * @ORM\Column(type="string")
            */
    public $employment_form;

    /**
            * @ORM\Column(type="text")
            */
    public $entry_interview;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $parent_id;

    /**
            * @ORM\Column(type="string")
            */
    public $parent_type;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $recruitment_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $recruitment_end_id;

    /**
        * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidatures")
        */
    public $modified_user_link;

    /**
        * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidatures")
        */
    public $created_by_link;

    /**
        * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidatures")
        */
    public $assigned_user_link;

    /**
        * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
        */
    public Collection $SecurityGroups;

    /**
        * @ORM\JoinColumn(name="employee_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Employees::class, inversedBy="candidatures")
        */
    public $employee_link;

    /**
        * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Candidates::class, inversedBy="candidatures")
        */
    public $candidate;

    /**
        * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Employees::class, inversedBy="candidatures")
        */
    public $employee;

    /**
        * @ORM\OneToMany(targetEntity=Calls::class, mappedBy="candidatures")
        */
    public Collection $calls;

    /**
        * @ORM\OneToMany(targetEntity=Meetings::class, mappedBy="candidatures")
        */
    public Collection $meetings;

    /**
        * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="candidatures")
        */
    public Collection $notes;

    /**
        * @ORM\OneToMany(targetEntity=Tasks::class, mappedBy="candidatures")
        */
    public Collection $tasks;

    /**
        * @ORM\JoinColumn(name="recruitment_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Recruitments::class, inversedBy="candidatures")
        */
    public $recruitments;

    /**
        * @ORM\JoinColumn(name="recruitment_end_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Recruitments::class, inversedBy="candidatures")
        */
    public $recruitments_end;

    /**
        * @ORM\OneToMany(targetEntity=Emails::class, mappedBy="candidatures")
        */
    public Collection $emails;

    /**
        * @ORM\OneToMany(targetEntity=Appraisals::class, mappedBy="candidatures")
        */
    public Collection $appraisals;

    /**
        * @ORM\JoinTable(name="documents_candidatures", joinColumns={@ORM\JoinColumn(name="candidature_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="document_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Documents::class, inversedBy="candidatures")
        */
    public Collection $documents;

    /**
        * @ORM\OneToMany(targetEntity=Files::class, mappedBy="candidatures")
        */
    public Collection $files;


public function __construct()
{
        $this->SecurityGroups = new ArrayCollection();
        $this->calls = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->emails = new ArrayCollection();
        $this->appraisals = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->files = new ArrayCollection();
    }
}