<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="candidates_cstm", indexes={
 * @ORM\Index(name="candidatespk", columns={"id_c"})})
 * @property mixed $code_type_c
 * @property mixed $favorited_game_c
 * @property mixed $testowe_c
 */
// Auto-generated SectionRepository section end
class Candidates_cstm extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\Column(name="id_c", type="string", length=36)
     * @ORM\GeneratedValue(strategy="NONE")
     */
    protected $id;


    /**
     * @ORM\OneToOne(targetEntity="Candidates", inversedBy="custom_entity")
     * @ORM\JoinColumn(name="id_c", referencedColumnName="id")
     */
    protected $main_entity;


    /**
     * @ORM\Column(type="multienum")
     */
    protected $code_type_c;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $favorited_game_c;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $testowe_c;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
    }

                public function getMainEntity()
    {
        return $this->main_entity;
    }

    public function setMainEntity($main_entity)
    {
        $this->main_entity = $main_entity;

        if ($main_entity && $main_entity->getCustomEntity() !== $this) {
            $main_entity->setCustomEntity($this);
        }

        return $this;
    }

            public function getEmail1(): string
        {
            $conn = $this->getEntityManager()->getConnection();

            $sql = '
                SELECT ea.email_address
                FROM email_addresses ea
                INNER JOIN email_addr_bean_rel eabr
                    ON eabr.email_address_id = ea.id
                WHERE eabr.bean_id = :bean_id
                AND eabr.bean_module = :bean_module
                AND eabr.primary_address = :primary_address
                AND eabr.deleted = :deleted
                LIMIT 1
            ';

            $module_name = $this->getModuleName();
            if (in_array($module_name, ['Employees'])) {
                $module_name = 'Users';
            }

            $stmt = $conn->prepare($sql);
            $result = $stmt->executeQuery([
                'bean_id' => $this->id,
                'bean_module' => $module_name,
                'primary_address' => 1,
                'deleted' => 0,
            ]);

            return $result->fetchOne() ?: '';
}

public function getSerialized(bool $json = false): array|string
{
    $data = parent::getSerialized($json);
    $data['email1'] = $this->getEmail1();
    return $data;
}
    // Auto-generated SectionMethods section end
}
