<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="candidatures", indexes={
 * @ORM\Index(name="candidaturespk", columns={"id"})})
 * @property mixed $id
 * @property mixed $name
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $date_indexed
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $description
 * @property mixed $deleted
 * @property mixed $assigned_user_id
 * @property mixed $employee_id
 * @property mixed $currency_id
 * @property mixed $reason_for_rejection
 * @property mixed $dg_amount
 * @property mixed $dg_amount_usdollar
 * @property mixed $gross_amount
 * @property mixed $gross_amount_usdollar
 * @property mixed $net_amount
 * @property mixed $net_amount_usdollar
 * @property mixed $notice
 * @property mixed $notice_final_expectations
 * @property mixed $salary_net
 * @property mixed $salary_net_usdollar
 * @property mixed $scoring
 * @property mixed $source
 * @property mixed $start_date
 * @property mixed $work_start
 * @property mixed $training_date
 * @property mixed $status
 * @property mixed $status_information
 * @property mixed $task_grade
 * @property mixed $to_decision
 * @property mixed $final_employment_form
 * @property mixed $employment_form
 * @property mixed $entry_interview
 * @property mixed $route_of_acquisition
 * @property mixed $original_candidature_id
 * @property mixed $parent_id
 * @property mixed $parent_type
 * @property mixed $recruitment_id
 */
// Auto-generated SectionRepository section end
class Candidatures extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="text")
     */
    protected $description;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $assigned_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $employee_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $currency_id;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $reason_for_rejection;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $dg_amount;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $dg_amount_usdollar;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $gross_amount;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $gross_amount_usdollar;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $net_amount;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $net_amount_usdollar;

    /**
     * @ORM\Column(type="text")
     */
    protected $notice;

    /**
     * @ORM\Column(type="text")
     */
    protected $notice_final_expectations;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $salary_net;

    /**
     * @ORM\Column(type="decimal")
     */
    protected $salary_net_usdollar;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $scoring;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $source;

    /**
     * @ORM\Column(type="date")
     */
    protected $start_date;

    /**
     * @ORM\Column(type="date")
     */
    protected $work_start;

    /**
     * @ORM\Column(type="date")
     */
    protected $training_date;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $status;

    /**
     * @ORM\Column(type="text")
     */
    protected $status_information;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $task_grade;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $to_decision;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $final_employment_form;

    /**
     * @ORM\Column(type="multienum")
     */
    protected $employment_form;

    /**
     * @ORM\Column(type="text")
     */
    protected $entry_interview;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $route_of_acquisition;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $original_candidature_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $parent_id;

    /**
     * @ORM\Column(type="string")
     */
    protected $parent_type;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $recruitment_id;

    /**
     * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidatures")
     */
    protected $modified_user_link;

    /**
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidatures")
     */
    protected $created_by_link;

    /**
     * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="candidatures")
     */
    protected $assigned_user_link;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\JoinColumn(name="employee_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Employees::class, inversedBy="candidatures")
     */
    protected $employee_link;

    /**
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Candidates::class, inversedBy="candidatures")
     */
    protected $candidate;

    /**
     * @ORM\OneToMany(targetEntity=Calls::class, mappedBy="calls")
     */
    protected Collection $calls;

    /**
     * @ORM\OneToMany(targetEntity=Meetings::class, mappedBy="meetings")
     */
    protected Collection $meetings;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="notes")
     */
    protected Collection $notes;

    /**
     * @ORM\OneToMany(targetEntity=Tasks::class, mappedBy="tasks")
     */
    protected Collection $tasks;

    /**
     * @ORM\JoinColumn(name="recruitment_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Recruitments::class, inversedBy="candidatures")
     */
    protected $recruitments;

    /**
     * @ORM\OneToMany(targetEntity=Emails::class, mappedBy="emails")
     */
    protected Collection $emails;

    /**
     * @ORM\OneToMany(targetEntity=Appraisals::class, mappedBy="candidatures")
     */
    protected Collection $appraisals;

    /**
     * @ORM\JoinTable(name="documents_candidatures", joinColumns={@ORM\JoinColumn(name="candidature_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="document_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Documents::class, inversedBy="candidatures")
     */
    protected Collection $documents;

    /**
     * @ORM\OneToMany(targetEntity=Files::class, mappedBy="candidature")
     */
    protected Collection $files;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->SecurityGroups = new ArrayCollection();
        $this->calls = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->emails = new ArrayCollection();
        $this->appraisals = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->files = new ArrayCollection();
    }

    // Auto-generated SectionMethods section end
}
