<?php
// Generated by the Entity Creator: 2025-06-09 11:19:24

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity
 * @ORM\Table(name="comments", indexes={
 *   @ORM\Index(name="commentspk", columns={"id"})})
 */
class Comments
{
    /**
        * @ORM\Id
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $name;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_entered;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_indexed;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $modified_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $created_by;

    /**
            * @ORM\Column(type="text")
            */
    public $description;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $assigned_user_id;

    /**
                    * @ORM\ManyToOne(targetEntity=Comments::class, inversedBy="reply_to")
        * @ORM\JoinColumn(name="reply_to_id", referencedColumnName="id")
            */
    public $reply_to_id;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $parent_type;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $parent_id;

    /**
            * @ORM\Column(type="boolean")
            */
    public $pinned;

    /**
            * @ORM\Column(type="boolean")
            */
    public $removed;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_edited;

    /**
        * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="comments")
        */
    public $modified_user_link;

    /**
        * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="comments")
        */
    public $created_by_link;

    /**
        * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="comments")
        */
    public $assigned_user_link;

    /**
        * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="reply_to_id")
        */
    public Collection $reply_to;

    /**
        * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=News::class, inversedBy="comments")
        */
    public $news;


public function __construct()
{
        $this->reply_to = new ArrayCollection();
    }
}