<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="delegations", indexes={
 * @ORM\Index(name="delegationspk", columns={"id"}), 
 * @ORM\Index(name="idx_delegation_locale_id", columns={"delegation_locale_id"})})
 * @property mixed $id
 * @property mixed $name
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $date_indexed
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $description
 * @property mixed $deleted
 * @property mixed $assigned_user_id
 * @property mixed $delegation_id
 * @property mixed $purpose
 * @property mixed $start_date
 * @property mixed $end_date
 * @property mixed $transport_cost
 * @property mixed $transport_cost_usdollar
 * @property mixed $currency_id
 * @property mixed $regiments
 * @property mixed $regiments_usdollar
 * @property mixed $restaurant_bills
 * @property mixed $accomodations
 * @property mixed $total_accommodation
 * @property mixed $total_accommodation_usdollar
 * @property mixed $accommodation_lump_sum
 * @property mixed $accommodation_lump_sum_usdollar
 * @property mixed $other
 * @property mixed $other_usdollar
 * @property mixed $total_expenses
 * @property mixed $total_expenses_usdollar
 * @property mixed $obtained_sum
 * @property mixed $obtained_sum_usdollar
 * @property mixed $payoff_sum
 * @property mixed $payoff_sum_usdollar
 * @property mixed $return_sum
 * @property mixed $return_sum_usdollar
 * @property mixed $regimen_value
 * @property mixed $regimen_value_usdollar
 * @property mixed $accommodation_value
 * @property mixed $accommodation_value_usdollar
 * @property mixed $obtained_sum_usdollars
 * @property mixed $owner
 * @property mixed $exchange_rate
 * @property mixed $assured_number_of_breakfasts
 * @property mixed $assured_number_of_dinners
 * @property mixed $assured_number_of_suppers
 * @property mixed $assured_number_of_accommodations
 * @property mixed $costs_sum
 * @property mixed $delegation_locale_id
 */
// Auto-generated SectionRepository section end
class Delegations extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="text")
     */
    protected $description;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $assigned_user_id;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $delegation_id;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $purpose;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $end_date;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $transport_cost;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $transport_cost_usdollar;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $currency_id;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $regiments;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $regiments_usdollar;

    /**
     * @ORM\Column(type="integer", length="255")
     */
    protected $restaurant_bills;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $accomodations;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $total_accommodation;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $total_accommodation_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $accommodation_lump_sum;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $accommodation_lump_sum_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $other;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $other_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $total_expenses;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $total_expenses_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $obtained_sum;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $obtained_sum_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $payoff_sum;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $payoff_sum_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $return_sum;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $return_sum_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $regimen_value;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $regimen_value_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $accommodation_value;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $accommodation_value_usdollar;

    /**
     * @ORM\Column(type="decimal", length="26")
     */
    protected $obtained_sum_usdollars;

    /**
     * @ORM\Column(type="boolean", length="255")
     */
    protected $owner;

    /**
     * @ORM\Column(type="float", length="18")
     */
    protected $exchange_rate;

    /**
     * @ORM\Column(type="integer", length="255")
     */
    protected $assured_number_of_breakfasts;

    /**
     * @ORM\Column(type="integer", length="255")
     */
    protected $assured_number_of_dinners;

    /**
     * @ORM\Column(type="integer", length="255")
     */
    protected $assured_number_of_suppers;

    /**
     * @ORM\Column(type="integer", length="255")
     */
    protected $assured_number_of_accommodations;

    /**
     * @ORM\Column(type="float", length="18")
     */
    protected $costs_sum;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $delegation_locale_id;

    /**
     * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="delegations")
     */
    protected $modified_user_link;

    /**
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="delegations")
     */
    protected $created_by_link;

    /**
     * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="delegations")
     */
    protected $assigned_user_link;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\JoinColumn(name="delegation_locale_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=DelegationsLocale::class, inversedBy="delegations")
     */
    protected $delegationslocale;

    /**
     * @ORM\OneToMany(targetEntity=WorkSchedules::class, mappedBy="delegations")
     */
    protected Collection $workschedules;

    /**
     * @ORM\JoinTable(name="documents_delegations", joinColumns={@ORM\JoinColumn(name="delegation_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="document_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Documents::class, inversedBy="delegations")
     */
    protected Collection $documents;

    /**
     * @ORM\OneToMany(targetEntity=Costs::class, mappedBy="delegations")
     */
    protected Collection $costs;

    /**
     * @ORM\OneToMany(targetEntity=Transportations::class, mappedBy="delegations")
     */
    protected Collection $transportations;

    /**
     * @ORM\OneToMany(targetEntity=Reservations::class, mappedBy="delegations")
     */
    protected Collection $reservations;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->SecurityGroups = new ArrayCollection();
        $this->workschedules = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->costs = new ArrayCollection();
        $this->transportations = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    // Auto-generated SectionMethods section end
}
