<?php
// Generated by the Entity Creator: 2025-06-09 11:19:24

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="document_revisions", indexes={
 *   @ORM\Index(name="documentrevisionspk", columns={"id"}), 
 *   @ORM\Index(name="documentrevision_mimetype", columns={"file_mime_type"})})
 */
class DocumentRevisions
{
    /**
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $change_log;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $document_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $doc_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $doc_type;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $doc_url;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_entered;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $created_by;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $filename;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $file_ext;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $file_mime_type;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $revision;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
        * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="document_revisions")
        */
    public $created_by_link;

    /**
        * @ORM\JoinColumn(name="document_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Documents::class, inversedBy="document_revisions")
        */
    public $documents;


public function __construct()
{
    }
}