<?php
// Generated by the Entity Creator: 2025-06-09 11:19:24

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity
 * @ORM\Table(name="documents", indexes={
 *   @ORM\Index(name="documentspk", columns={"id"}), 
 *   @ORM\Index(name="idx_doc_cat", columns={"category_id", "subcategory_id"})})
 */
class Documents
{
    /**
        * @ORM\Id
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_entered;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_indexed;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $modified_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $created_by;

    /**
            * @ORM\Column(type="text")
            */
    public $description;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $assigned_user_id;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $document_name;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $doc_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $doc_type;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $doc_url;

    /**
            * @ORM\Column(type="date")
            */
    public $active_date;

    /**
            * @ORM\Column(type="date")
            */
    public $exp_date;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $category_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $subcategory_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $status_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $document_revision_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $related_doc_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $related_doc_rev_id;

    /**
            * @ORM\Column(type="boolean")
            */
    public $is_template;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $template_type;

    /**
        * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="documents")
        */
    public $modified_user_link;

    /**
        * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="documents")
        */
    public $created_by_link;

    /**
        * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="documents")
        */
    public $assigned_user_link;

    /**
        * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
        */
    public Collection $SecurityGroups;

    /**
        * @ORM\OneToMany(targetEntity=DocumentRevisions::class, mappedBy="documents")
        */
    public Collection $revisions;

    /**
        * @ORM\JoinTable(name="documents_contracts")
        * @ORM\ManyToMany(targetEntity=Contracts::class, mappedBy="documents")
        */
    public Collection $contracts;

    /**
        * @ORM\JoinTable(name="documents_delegations")
        * @ORM\ManyToMany(targetEntity=Delegations::class, mappedBy="documents")
        */
    public Collection $delegations;

    /**
        * @ORM\JoinTable(name="positions_documents", joinColumns={@ORM\JoinColumn(name="documents_rhs_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="positions_lhs_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Positions::class, inversedBy="documents")
        */
    public Collection $positions;

    /**
        * @ORM\JoinTable(name="trainings_documents", joinColumns={@ORM\JoinColumn(name="document_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="training_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Trainings::class, inversedBy="documents")
        */
    public Collection $trainings;

    /**
        * @ORM\JoinTable(name="exitinterviews_documents", joinColumns={@ORM\JoinColumn(name="document_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="exitinterview_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=ExitInterviews::class, inversedBy="documents")
        */
    public Collection $exitinterviews;

    /**
        * @ORM\JoinTable(name="appraisals_documents", joinColumns={@ORM\JoinColumn(name="document_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="appraisal_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Appraisals::class, inversedBy="documents")
        */
    public Collection $appraisals;

    /**
        * @ORM\JoinTable(name="documents_certificates")
        * @ORM\ManyToMany(targetEntity=Certificates::class, mappedBy="documents")
        */
    public Collection $certificates;

    /**
        * @ORM\JoinTable(name="documents_candidates")
        * @ORM\ManyToMany(targetEntity=Candidates::class, mappedBy="documents")
        */
    public Collection $candidates;

    /**
        * @ORM\JoinTable(name="documents_candidatures")
        * @ORM\ManyToMany(targetEntity=Candidatures::class, mappedBy="documents")
        */
    public Collection $candidatures;

    /**
        * @ORM\JoinTable(name="documents_termsofemployment")
        * @ORM\ManyToMany(targetEntity=TermsOfEmployment::class, mappedBy="documents")
        */
    public Collection $termsofemployment;


public function __construct()
{
        $this->SecurityGroups = new ArrayCollection();
        $this->revisions = new ArrayCollection();
        $this->contracts = new ArrayCollection();
        $this->delegations = new ArrayCollection();
        $this->positions = new ArrayCollection();
        $this->trainings = new ArrayCollection();
        $this->exitinterviews = new ArrayCollection();
        $this->appraisals = new ArrayCollection();
        $this->certificates = new ArrayCollection();
        $this->candidates = new ArrayCollection();
        $this->candidatures = new ArrayCollection();
        $this->termsofemployment = new ArrayCollection();
    }
}