<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="emails", indexes={
 * @ORM\Index(name="emailspk", columns={"id"}), 
 * @ORM\Index(name="idx_email_name", columns={"name"}), 
 * @ORM\Index(name="idx_message_id", columns={"message_id"}), 
 * @ORM\Index(name="idx_email_parent_id", columns={"parent_id"}), 
 * @ORM\Index(name="idx_email_assigned", columns={"assigned_user_id", "type", "status"}), 
 * @ORM\Index(name="idx_email_cat", columns={"category_id"}), 
 * @ORM\Index(name="dlnc_email", columns={"id", "deleted", "status", "date_sent_received"}), 
 * @ORM\Index(name="idx_email_uid", columns={"uid"})})
 * @property mixed $id
 * @property mixed $name
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $date_indexed
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $deleted
 * @property mixed $assigned_user_id
 * @property mixed $orphaned
 * @property mixed $last_synced
 * @property mixed $date_sent_received
 * @property mixed $message_id
 * @property mixed $type
 * @property mixed $status
 * @property mixed $flagged
 * @property mixed $reply_to_status
 * @property mixed $intent
 * @property mixed $mailbox_id
 * @property mixed $parent_type
 * @property mixed $parent_id
 * @property mixed $uid
 * @property mixed $category_id
 */
// Auto-generated SectionRepository section end
class Emails extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $assigned_user_id;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $orphaned;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $last_synced;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_sent_received;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $message_id;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $type;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $status;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $flagged;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $reply_to_status;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $intent;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $mailbox_id;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $parent_type;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $parent_id;

    /**
     * @ORM\Column(type="string")
     */
    protected $uid;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $category_id;

    /**
     * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="emails")
     */
    protected $modified_user_link;

    /**
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="emails")
     */
    protected $created_by_link;

    /**
     * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="emails")
     */
    protected $assigned_user_link;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="emails")
     */
    protected Collection $notes;

    /**
     * @ORM\JoinTable(name="emails_beans")
     * @ORM\ManyToMany(targetEntity=Employees::class, mappedBy="emails")
     */
    protected Collection $employees;

    /**
     * @ORM\JoinTable(name="emails_beans")
     * @ORM\ManyToMany(targetEntity=Meetings::class, mappedBy="emails")
     */
    protected Collection $meetings;

    /**
     * @ORM\JoinTable(name="emails_beans", joinColumns={@ORM\JoinColumn(name="email_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="bean_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Candidates::class, inversedBy="emails")
     */
    protected Collection $candidates;

    /**
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Recruitments::class, inversedBy="emails")
     */
    protected $recruitments;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->SecurityGroups = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->employees = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->candidates = new ArrayCollection();
    }

    // Auto-generated SectionMethods section end
}
