<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="email_marketing", indexes={
 * @ORM\Index(name="emmkpk", columns={"id"}), 
 * @ORM\Index(name="idx_emmkt_name", columns={"name"}), 
 * @ORM\Index(name="idx_emmkit_del", columns={"deleted"})})
 * @property mixed $id
 * @property mixed $deleted
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $name
 * @property mixed $from_name
 * @property mixed $from_addr
 * @property mixed $reply_to_name
 * @property mixed $reply_to_addr
 * @property mixed $inbound_email_id
 * @property mixed $date_start
 * @property mixed $template_id
 * @property mixed $status
 * @property mixed $campaign_id
 * @property mixed $outbound_email_id
 * @property mixed $all_prospect_lists
 */
// Auto-generated SectionRepository section end
class EmailMarketing extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $from_name;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $from_addr;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $reply_to_name;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $reply_to_addr;

    /**
     * @ORM\Column(type="string", length="36")
     */
    protected $inbound_email_id;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_start;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $template_id;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $status;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $campaign_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $outbound_email_id;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $all_prospect_lists;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\JoinColumn(name="template_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=EmailTemplates::class, inversedBy="email_marketing")
     */
    protected $emailtemplate;

    /**
     * @ORM\JoinTable(name="email_marketing_prospect_lists")
     * @ORM\ManyToMany(targetEntity=ProspectLists::class, mappedBy="email_marketing")
     */
    protected Collection $prospectlists;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->SecurityGroups = new ArrayCollection();
        $this->prospectlists = new ArrayCollection();
    }

    // Auto-generated SectionMethods section end
}
