<?php
// Generated by the Entity Creator: 2025-06-09 11:19:24

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity
 * @ORM\Table(name="meetings", indexes={
 *   @ORM\Index(name="meetingspk", columns={"id"}), 
 *   @ORM\Index(name="idx_mtg_name", columns={"name"}), 
 *   @ORM\Index(name="idx_meet_par_del", columns={"parent_id", "parent_type", "deleted"}), 
 *   @ORM\Index(name="idx_meet_stat_del", columns={"assigned_user_id", "status", "deleted"}), 
 *   @ORM\Index(name="idx_meet_date_start", columns={"date_start"})})
 */
class Meetings
{
    /**
        * @ORM\Id
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $name;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_entered;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_indexed;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $modified_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $created_by;

    /**
            * @ORM\Column(type="text")
            */
    public $description;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $assigned_user_id;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $location;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $password;

    /**
            * @ORM\Column(type="string", length="200")
            */
    public $join_url;

    /**
            * @ORM\Column(type="string", length="400")
            */
    public $host_url;

    /**
            * @ORM\Column(type="string", length="400")
            */
    public $displayed_url;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $creator;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $external_id;

    /**
            * @ORM\Column(type="integer", length="3")
            */
    public $duration_hours;

    /**
            * @ORM\Column(type="integer", length="2")
            */
    public $duration_minutes;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_start;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_end;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $parent_type;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $status;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $parent_id;

    /**
            * @ORM\Column(type="integer")
            */
    public $reminder_time;

    /**
            * @ORM\Column(type="integer")
            */
    public $email_reminder_time;

    /**
            * @ORM\Column(type="boolean")
            */
    public $email_reminder_sent;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $outlook_id;

    /**
            * @ORM\Column(type="integer", length="11")
            */
    public $sequence;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $repeat_type;

    /**
            * @ORM\Column(type="integer", length="3")
            */
    public $repeat_interval;

    /**
            * @ORM\Column(type="string", length="7")
            */
    public $repeat_dow;

    /**
            * @ORM\Column(type="date")
            */
    public $repeat_until;

    /**
            * @ORM\Column(type="integer", length="7")
            */
    public $repeat_count;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $repeat_parent_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $recurring_source;

    /**
            * @ORM\Column(type="string")
            */
    public $duration;

    /**
            * @ORM\Column(type="string", length="1024")
            */
    public $gsync_id;

    /**
            * @ORM\Column(type="integer")
            */
    public $gsync_lastsync;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $type;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $jjwg_maps_address_c;

    /**
            * @ORM\Column(type="float", length="10")
            */
    public $jjwg_maps_lat_c;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $jjwg_maps_geocode_status_c;

    /**
            * @ORM\Column(type="float", length="11")
            */
    public $jjwg_maps_lng_c;

    /**
        * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="meetings")
        */
    public $modified_user_link;

    /**
        * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="meetings")
        */
    public $created_by_link;

    /**
        * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="meetings")
        */
    public $assigned_user_link;

    /**
        * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
        */
    public Collection $SecurityGroups;

    /**
        * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="meetings")
        */
    public Collection $notes;

    /**
        * @ORM\JoinTable(name="meetings_users")
        * @ORM\ManyToMany(targetEntity=Users::class, mappedBy="meetings")
        */
    public Collection $users;

    /**
        * @ORM\JoinTable(name="trainings_meetings", joinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="training_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Trainings::class, inversedBy="meetings")
        */
    public Collection $trainings;

    /**
        * @ORM\JoinTable(name="exitinterviews_meetings", joinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="exitinterview_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=ExitInterviews::class, inversedBy="meetings")
        */
    public Collection $exitinterviews;

    /**
        * @ORM\JoinTable(name="appraisals_meetings", joinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="appraisal_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=Appraisals::class, inversedBy="meetings")
        */
    public Collection $appraisals;

    /**
        * @ORM\JoinTable(name="meetings_candidates")
        * @ORM\ManyToMany(targetEntity=Candidates::class, mappedBy="meetings")
        */
    public Collection $candidates;

    /**
        * @ORM\OneToMany(targetEntity=Conclusions::class, mappedBy="meetings")
        */
    public Collection $conclusions;

    /**
        * @ORM\OneToMany(targetEntity=Reservations::class, mappedBy="meetings")
        */
    public Collection $reservations;

    /**
        * @ORM\JoinTable(name="meetings_resources")
        * @ORM\ManyToMany(targetEntity=Resources::class, mappedBy="meetings")
        */
    public Collection $resources;


public function __construct()
{
        $this->SecurityGroups = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->trainings = new ArrayCollection();
        $this->exitinterviews = new ArrayCollection();
        $this->appraisals = new ArrayCollection();
        $this->candidates = new ArrayCollection();
        $this->conclusions = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->resources = new ArrayCollection();
    }
}