<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="meetings", indexes={
 * @ORM\Index(name="meetingspk", columns={"id"}), 
 * @ORM\Index(name="idx_mtg_name", columns={"name"}), 
 * @ORM\Index(name="idx_meet_par_del", columns={"parent_id", "parent_type", "deleted"}), 
 * @ORM\Index(name="idx_meet_stat_del", columns={"assigned_user_id", "status", "deleted"}), 
 * @ORM\Index(name="idx_meet_date_start", columns={"date_start"})})
 * @property mixed $id
 * @property mixed $name
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $date_indexed
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $description
 * @property mixed $deleted
 * @property mixed $assigned_user_id
 * @property mixed $location
 * @property mixed $password
 * @property mixed $join_url
 * @property mixed $host_url
 * @property mixed $displayed_url
 * @property mixed $creator
 * @property mixed $external_id
 * @property mixed $duration_hours
 * @property mixed $duration_minutes
 * @property mixed $date_start
 * @property mixed $date_end
 * @property mixed $parent_type
 * @property mixed $status
 * @property mixed $parent_id
 * @property mixed $reminder_time
 * @property mixed $email_reminder_time
 * @property mixed $email_reminder_sent
 * @property mixed $outlook_id
 * @property mixed $sequence
 * @property mixed $recurring_source
 * @property mixed $duration
 * @property mixed $gsync_id
 * @property mixed $gsync_lastsync
 * @property mixed $type
 * @property mixed $repeat_type
 * @property mixed $repeat_interval
 * @property mixed $repeat_dow
 * @property mixed $repeat_until
 * @property mixed $repeat_count
 * @property mixed $repeat_parent_id
 */
// Auto-generated SectionRepository section end
class Meetings extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\OneToOne(
     *     targetEntity="Meetings_cstm",
     *     mappedBy="main_entity",
     *     cascade={"persist", "remove"},
     *     fetch="EAGER"
     * )
     */
    protected $custom_entity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="text")
     */
    protected $description;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $assigned_user_id;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $location;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $password;

    /**
     * @ORM\Column(type="string", length="200")
     */
    protected $join_url;

    /**
     * @ORM\Column(type="string", length="400")
     */
    protected $host_url;

    /**
     * @ORM\Column(type="string", length="400")
     */
    protected $displayed_url;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $creator;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $external_id;

    /**
     * @ORM\Column(type="integer", length="3")
     */
    protected $duration_hours;

    /**
     * @ORM\Column(type="integer", length="2")
     */
    protected $duration_minutes;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_start;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_end;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $parent_type;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $status;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $parent_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $reminder_time;

    /**
     * @ORM\Column(type="integer")
     */
    protected $email_reminder_time;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $email_reminder_sent;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $outlook_id;

    /**
     * @ORM\Column(type="integer", length="11")
     */
    protected $sequence;

    /**
     * @ORM\Column(type="string", length="36")
     */
    protected $recurring_source;

    /**
     * @ORM\Column(type="string")
     */
    protected $duration;

    /**
     * @ORM\Column(type="string", length="1024")
     */
    protected $gsync_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $gsync_lastsync;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $type;

    /**
     * @ORM\Column(type="string", length="36")
     */
    protected $repeat_type;

    /**
     * @ORM\Column(type="integer", length="3")
     */
    protected $repeat_interval;

    /**
     * @ORM\Column(type="string", length="7")
     */
    protected $repeat_dow;

    /**
     * @ORM\Column(type="date")
     */
    protected $repeat_until;

    /**
     * @ORM\Column(type="integer", length="7")
     */
    protected $repeat_count;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $repeat_parent_id;

    /**
     * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="meetings")
     */
    protected $modified_user_link;

    /**
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="meetings")
     */
    protected $created_by_link;

    /**
     * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="meetings")
     */
    protected $assigned_user_link;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="meetings")
     */
    protected Collection $notes;

    /**
     * @ORM\JoinTable(name="meetings_users")
     * @ORM\ManyToMany(targetEntity=Users::class, mappedBy="meetings")
     */
    protected Collection $users;

    /**
     * @ORM\JoinTable(name="trainings_meetings", joinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="training_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Trainings::class, inversedBy="meetings")
     */
    protected Collection $trainings;

    /**
     * @ORM\JoinTable(name="exitinterviews_meetings", joinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="exitinterview_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=ExitInterviews::class, inversedBy="meetings")
     */
    protected Collection $exitinterviews;

    /**
     * @ORM\JoinTable(name="appraisals_meetings", joinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="appraisal_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Appraisals::class, inversedBy="meetings")
     */
    protected Collection $appraisals;

    /**
     * @ORM\JoinTable(name="meetings_candidates")
     * @ORM\ManyToMany(targetEntity=Candidates::class, mappedBy="meetings")
     */
    protected Collection $candidates;

    /**
     * @ORM\OneToMany(targetEntity=Conclusions::class, mappedBy="meetings")
     */
    protected Collection $conclusions;

    /**
     * @ORM\OneToMany(targetEntity=Reservations::class, mappedBy="reservations")
     */
    protected Collection $reservations;

    /**
     * @ORM\JoinTable(name="meetings_resources")
     * @ORM\ManyToMany(targetEntity=Resources::class, mappedBy="meetings")
     */
    protected Collection $resources;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->SecurityGroups = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->trainings = new ArrayCollection();
        $this->exitinterviews = new ArrayCollection();
        $this->appraisals = new ArrayCollection();
        $this->candidates = new ArrayCollection();
        $this->conclusions = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->resources = new ArrayCollection();
        $this->setCustomEntity(new Meetings_cstm());
    }

                public function getCustomEntity()
    {
        return $this->custom_entity;
    }


    public function setCustomEntity($custom_entity)
    {
        $this->custom_entity = $custom_entity;

        if ($custom_entity && $custom_entity->getMainEntity() !== $this) {
            $custom_entity->setMainEntity($this);
        }

        return $this;
    }

            // Auto-generated SectionMethods section end
}
