<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity
 * @ORM\Table(name="project_task", indexes={
 * @ORM\Index(name="proj_tasks_primary_key_idx", columns={"id"})})
 * @property mixed $id
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $date_indexed
 * @property mixed $project_id
 * @property mixed $project_task_id
 * @property mixed $name
 * @property mixed $status
 * @property mixed $relationship_type
 * @property mixed $description
 * @property mixed $predecessors
 * @property mixed $date_start
 * @property mixed $time_start
 * @property mixed $time_finish
 * @property mixed $date_finish
 * @property mixed $duration
 * @property mixed $duration_unit
 * @property mixed $actual_duration
 * @property mixed $percent_complete
 * @property mixed $date_due
 * @property mixed $parent_task_id
 * @property mixed $assigned_user_id
 * @property mixed $modified_user_id
 * @property mixed $priority
 * @property mixed $created_by
 * @property mixed $milestone_flag
 * @property mixed $order_number
 * @property mixed $task_number
 * @property mixed $estimated_effort
 * @property mixed $actual_effort
 * @property mixed $deleted
 * @property mixed $utilization
 */
// Auto-generated SectionRepository section end
class ProjectTask extends MintEntity
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $project_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $project_task_id;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $name;

    /**
     * @ORM\Column(type="string")
     */
    protected $status;

    /**
     * @ORM\Column(type="string")
     */
    protected $relationship_type;

    /**
     * @ORM\Column(type="text")
     */
    protected $description;

    /**
     * @ORM\Column(type="text")
     */
    protected $predecessors;

    /**
     * @ORM\Column(type="date")
     */
    protected $date_start;

    /**
     * @ORM\Column(type="integer")
     */
    protected $time_start;

    /**
     * @ORM\Column(type="integer")
     */
    protected $time_finish;

    /**
     * @ORM\Column(type="date")
     */
    protected $date_finish;

    /**
     * @ORM\Column(type="integer")
     */
    protected $duration;

    /**
     * @ORM\Column(type="text")
     */
    protected $duration_unit;

    /**
     * @ORM\Column(type="integer")
     */
    protected $actual_duration;

    /**
     * @ORM\Column(type="integer")
     */
    protected $percent_complete;

    /**
     * @ORM\Column(type="date")
     */
    protected $date_due;

    /**
     * @ORM\Column(type="integer")
     */
    protected $parent_task_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $assigned_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="string")
     */
    protected $priority;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $milestone_flag;

    /**
     * @ORM\Column(type="integer")
     */
    protected $order_number;

    /**
     * @ORM\Column(type="integer")
     */
    protected $task_number;

    /**
     * @ORM\Column(type="integer")
     */
    protected $estimated_effort;

    /**
     * @ORM\Column(type="integer")
     */
    protected $actual_effort;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="integer")
     */
    protected $utilization;

    /**
     * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="project_tasks")
     */
    protected Collection $notes;

    /**
     * @ORM\OneToMany(targetEntity=Tasks::class, mappedBy="project_tasks")
     */
    protected Collection $tasks;

    /**
     * @ORM\OneToMany(targetEntity=Meetings::class, mappedBy="meetings")
     */
    protected Collection $meetings;

    /**
     * @ORM\OneToMany(targetEntity=Calls::class, mappedBy="calls")
     */
    protected Collection $calls;

    /**
     * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="project_task")
     */
    protected $assigned_user_link;

    /**
     * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="project_task")
     */
    protected $modified_user_link;

    /**
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="project_task")
     */
    protected $created_by_link;

    /**
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Project::class, inversedBy="projecttask")
     */
    protected $projects;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->SecurityGroups = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->calls = new ArrayCollection();
    }

    // Auto-generated SectionMethods section end
}
