<?php
// Generated by the Entity Creator: 2025-06-09 11:19:24

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity
 * @ORM\Table(name="project", indexes={
 *   @ORM\Index(name="projects_primary_key_index", columns={"id"})})
 */
class Project
{
    /**
        * @ORM\Id
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_entered;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_indexed;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $assigned_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $modified_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $created_by;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $name;

    /**
            * @ORM\Column(type="text")
            */
    public $description;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="date")
            */
    public $estimated_start_date;

    /**
            * @ORM\Column(type="date")
            */
    public $estimated_end_date;

    /**
            * @ORM\Column(type="string")
            */
    public $status;

    /**
            * @ORM\Column(type="string")
            */
    public $priority;

    /**
            * @ORM\Column(type="boolean")
            */
    public $override_business_hours;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $jjwg_maps_address_c;

    /**
            * @ORM\Column(type="float", length="10")
            */
    public $jjwg_maps_lat_c;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $jjwg_maps_geocode_status_c;

    /**
            * @ORM\Column(type="float", length="11")
            */
    public $jjwg_maps_lng_c;

    /**
        * @ORM\JoinTable(name="securitygroups_records", joinColumns={@ORM\JoinColumn(name="record_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="securitygroups")
        */
    public Collection $SecurityGroups;

    /**
        * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="project")
        */
    public Collection $notes;

    /**
        * @ORM\OneToMany(targetEntity=Tasks::class, mappedBy="project")
        */
    public Collection $tasks;

    /**
        * @ORM\OneToMany(targetEntity=Meetings::class, mappedBy="project")
        */
    public Collection $meetings;

    /**
        * @ORM\OneToMany(targetEntity=Calls::class, mappedBy="project")
        */
    public Collection $calls;

    /**
        * @ORM\OneToMany(targetEntity=ProjectTask::class, mappedBy="project")
        */
    public Collection $projecttask;

    /**
        * @ORM\JoinColumn(name="assigned_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="project")
        */
    public $assigned_user_link;

    /**
        * @ORM\JoinColumn(name="modified_user_id", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="project")
        */
    public $modified_user_link;

    /**
        * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
        * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="project")
        */
    public $created_by_link;

    /**
        * @ORM\JoinTable(name="project_users_1_c")
        * @ORM\ManyToMany(targetEntity=Users::class, mappedBy="project")
        */
    public Collection $project_users_1;

    /**
        * @ORM\JoinTable(name="am_projecttemplates_project_1_c", joinColumns={@ORM\JoinColumn(name="am_projecttemplates_project_1project_idb", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="am_projecttemplates_project_1am_projecttemplates_ida", referencedColumnName="id")})
        * @ORM\ManyToMany(targetEntity=AM_ProjectTemplates::class, inversedBy="project")
        */
    public Collection $am_projecttemplates_project_1;


public function __construct()
{
        $this->SecurityGroups = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->calls = new ArrayCollection();
        $this->projecttask = new ArrayCollection();
        $this->project_users_1 = new ArrayCollection();
        $this->am_projecttemplates_project_1 = new ArrayCollection();
    }
}