<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

// Auto-generated SectionUse section start
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use League\OAuth2\Server\Entities\UserEntityInterface;
use MintHCM\Data\ORM\Doctrine\MintEntity\MintEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
// Auto-generated SectionUse section end
// Auto-generated SectionRepository section start

/**
 * @ORM\Entity(repositoryClass="MintHCM\Api\Repositories\UsersRepository")
 * @ORM\Table(name="users", indexes={
 * @ORM\Index(name="userspk", columns={"id"}), 
 * @ORM\Index(name="idx_user_name", columns={"user_name", "is_group", "status", "last_name", "first_name", "id"})})
 * @property mixed $id
 * @property mixed $user_name
 * @property mixed $user_hash
 * @property mixed $system_generated_password
 * @property mixed $pwd_last_changed
 * @property mixed $authenticate_id
 * @property mixed $sugar_login
 * @property mixed $first_name
 * @property mixed $last_name
 * @property mixed $date_indexed
 * @property mixed $is_admin
 * @property mixed $external_auth_only
 * @property mixed $receive_notifications
 * @property mixed $description
 * @property mixed $date_entered
 * @property mixed $date_modified
 * @property mixed $modified_user_id
 * @property mixed $created_by
 * @property mixed $title
 * @property mixed $photo
 * @property mixed $department
 * @property mixed $phone_home
 * @property mixed $phone_mobile
 * @property mixed $phone_work
 * @property mixed $phone_other
 * @property mixed $phone_fax
 * @property mixed $status
 * @property mixed $primary_address_street
 * @property mixed $primary_address_city
 * @property mixed $primary_address_state
 * @property mixed $primary_address_country
 * @property mixed $primary_address_postalcode
 * @property mixed $deleted
 * @property mixed $portal_only
 * @property mixed $show_on_employees
 * @property mixed $employee_status
 * @property mixed $messenger_id
 * @property mixed $messenger_type
 * @property mixed $reports_to_id
 * @property mixed $email1
 * @property mixed $business_role
 * @property mixed $is_group
 * @property mixed $factor_auth
 * @property mixed $factor_auth_interface
 * @property mixed $position_id
 * @property mixed $securitygroup_id
 * @property mixed $forced_tabs_dashboard_id
 * @property mixed $locked_dashboard_id
 * @property mixed $one_time_default_dashboard_id
 * @property mixed $birthdate
 * @property mixed $app_tokens
 */
// Auto-generated SectionRepository section end
class Users extends MintEntity implements UserEntityInterface
{

    // Auto-generated SectionProperties section start

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="id", length="36")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length="60")
     */
    protected $user_name;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $user_hash;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $system_generated_password;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $pwd_last_changed;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $authenticate_id;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $sugar_login;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $first_name;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $last_name;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_indexed;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $is_admin;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $external_auth_only;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $receive_notifications;

    /**
     * @ORM\Column(type="text")
     */
    protected $description;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_entered;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_modified;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $modified_user_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $created_by;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $title;

    /**
     * @ORM\Column(type="string", length="255")
     */
    protected $photo;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $department;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $phone_home;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $phone_mobile;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $phone_work;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $phone_other;

    /**
     * @ORM\Column(type="string", length="50")
     */
    protected $phone_fax;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $status;

    /**
     * @ORM\Column(type="string", length="150")
     */
    protected $primary_address_street;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $primary_address_city;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $primary_address_state;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $primary_address_country;

    /**
     * @ORM\Column(type="string", length="20")
     */
    protected $primary_address_postalcode;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $deleted;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $portal_only;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $show_on_employees;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $employee_status;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $messenger_id;

    /**
     * @ORM\Column(type="string", length="100")
     */
    protected $messenger_type;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="reports_to_link")
     * @ORM\JoinColumn(name="reports_to_id", referencedColumnName="id")
     */
    protected $reports_to_id;

    /**
     */
    protected $email1;

    /**
     * @ORM\Column(type="string")
     */
    protected $business_role;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $is_group;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $factor_auth;

    /**
     * @ORM\Column(type="string")
     */
    protected $factor_auth_interface;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $position_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $securitygroup_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $forced_tabs_dashboard_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $locked_dashboard_id;

    /**
     * @ORM\Column(type="id", length="36")
     */
    protected $one_time_default_dashboard_id;

    /**
     * @ORM\Column(type="date")
     */
    protected $birthdate;

    /**
     * @ORM\Column(type="text")
     */
    protected $app_tokens;

    /**
     * @ORM\OneToMany(targetEntity=Users::class, mappedBy="reports_to_id")
     */
    protected Collection $reports_to_link;

    /**
     * @ORM\JoinTable(name="email_addr_bean_rel", joinColumns={@ORM\JoinColumn(name="bean_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="email_address_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=EmailAddresses::class, inversedBy="email_addresses")
     */
    protected Collection $email_addresses;

    /**
     * @ORM\JoinTable(name="email_addr_bean_rel", joinColumns={@ORM\JoinColumn(name="bean_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="email_address_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=EmailAddresses::class, inversedBy="email_addresses")
     */
    protected Collection $email_addresses_primary;

    /**
     * @ORM\JoinTable(name="calls_users", joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="call_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Calls::class, inversedBy="users")
     */
    protected Collection $calls;

    /**
     * @ORM\JoinTable(name="meetings_users", joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Meetings::class, inversedBy="users")
     */
    protected Collection $meetings;

    /**
     * @ORM\OneToMany(targetEntity=Tasks::class, mappedBy="assigned_user_link")
     */
    protected Collection $tasks;

    /**
     * @ORM\JoinTable(name="acl_roles_users", joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="role_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=ACLRoles::class, inversedBy="users")
     */
    protected Collection $aclroles;

    /**
     * @ORM\OneToMany(targetEntity=EAPM::class, mappedBy="assigned_user_link")
     */
    protected Collection $eapm;

    /**
     * @ORM\OneToMany(targetEntity=OAuthTokens::class, mappedBy="assigned_user_link")
     */
    protected Collection $oauth_tokens;

    /**
     * @ORM\JoinTable(name="project_users_1_c", joinColumns={@ORM\JoinColumn(name="project_users_1users_idb", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="project_users_1project_ida", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Project::class, inversedBy="project_users_1")
     */
    protected Collection $project_users_1;

    /**
     * @ORM\JoinTable(name="am_projecttemplates_users_1_c", joinColumns={@ORM\JoinColumn(name="users_idb", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="am_projecttemplates_ida", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=AM_ProjectTemplates::class, inversedBy="am_projecttemplates_users_1")
     */
    protected Collection $am_projecttemplates_users_1;

    /**
     * @ORM\JoinTable(name="securitygroups_users", joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=SecurityGroups::class, inversedBy="users")
     */
    protected Collection $SecurityGroups;

    /**
     * @ORM\JoinColumn(name="position_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=Positions::class, inversedBy="employees")
     */
    protected $position;

    /**
     * @ORM\OneToMany(targetEntity=OnboardingOffboardingElements::class, mappedBy="users")
     */
    protected Collection $onboardingoffboardingelements;

    /**
     * @ORM\JoinTable(name="candidates_employees", joinColumns={@ORM\JoinColumn(name="employee_id", referencedColumnName="id")}, inverseJoinColumns={@ORM\JoinColumn(name="candidate_id", referencedColumnName="id")})
     * @ORM\ManyToMany(targetEntity=Candidates::class, inversedBy="employee")
     */
    protected Collection $candidates;

    /**
     * @ORM\JoinColumn(name="securitygroup_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=SecurityGroups::class, inversedBy="employees")
     */
    protected $securitygroups_employees_link;

    /**
     * @ORM\OneToMany(targetEntity=Ideas::class, mappedBy="users")
     */
    protected Collection $ideas;

    /**
     * @ORM\JoinColumn(name="forced_tabs_dashboard_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=DashboardManager::class, inversedBy="users_forced_tabs_dashboards")
     */
    protected $users_forced_tabs_dashboards;

    /**
     * @ORM\JoinColumn(name="locked_dashboard_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=DashboardManager::class, inversedBy="users_locked_dashboards")
     */
    protected $users_locked_dashboards;

    /**
     * @ORM\JoinColumn(name="one_time_default_dashboard_id", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity=DashboardManager::class, inversedBy="users_one_time_default_dashboards")
     */
    protected $users_one_time_default_dashboards;

    /**
     * @ORM\JoinTable(name="users_schedulereports")
     * @ORM\ManyToMany(targetEntity=ScheduleReports::class, mappedBy="users")
     */
    protected Collection $schedulereports;

    /**
     * @ORM\OneToMany(targetEntity=WorkSchedules::class, mappedBy="deputy")
     */
    protected Collection $deputy;

    // Auto-generated SectionProperties section end
    // Auto-generated SectionMethods section start
    public function __construct()
    {
        $this->reports_to_link = new ArrayCollection();
        $this->email_addresses = new ArrayCollection();
        $this->email_addresses_primary = new ArrayCollection();
        $this->calls = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->aclroles = new ArrayCollection();
        $this->eapm = new ArrayCollection();
        $this->oauth_tokens = new ArrayCollection();
        $this->project_users_1 = new ArrayCollection();
        $this->am_projecttemplates_users_1 = new ArrayCollection();
        $this->SecurityGroups = new ArrayCollection();
        $this->onboardingoffboardingelements = new ArrayCollection();
        $this->candidates = new ArrayCollection();
        $this->ideas = new ArrayCollection();
        $this->schedulereports = new ArrayCollection();
        $this->deputy = new ArrayCollection();
    }

    public function getIdentifier(): string
    {
        return $this->id;
    }


    /**
     * Get the fullname 
     *
     * @return string
     */
    public function getFullName(): string
    {
        $names = [];
        if (!empty($this->first_name)) {
            $names[] = $this->first_name;
        }
        if (!empty($this->last_name)) {
            $names[] = $this->last_name;
        }

        return !empty($names) ? implode(' ', $names) : '';
    }


    public function getName(): ?string
    {
        return $this->getFullName();
    }


    /**
     * Check that password matches existing hash
     * @param string $password Plaintext password
     */
    public function checkPassword(string $password): bool
    {
        if (empty($this->user_hash)) {
            return false;
        }

        $passwordMd5 = md5($password);
        if ($this->user_hash[0] !== '$' && strlen($this->user_hash) === 32) {
            // Legacy md5 password
            return strtolower($passwordMd5) === $this->user_hash;
        }

        return password_verify(strtolower($passwordMd5), $this->user_hash);
    }

        public function getEmail1(): string
        {
            $conn = $this->getEntityManager()->getConnection();

            $sql = '
                SELECT ea.email_address
                FROM email_addresses ea
                INNER JOIN email_addr_bean_rel eabr
                    ON eabr.email_address_id = ea.id
                WHERE eabr.bean_id = :bean_id
                AND eabr.bean_module = :bean_module
                AND eabr.primary_address = :primary_address
                AND eabr.deleted = :deleted
                LIMIT 1
            ';

            $module_name = $this->getModuleName();
            if (in_array($module_name, ['Employees'])) {
                $module_name = 'Users';
            }

            $stmt = $conn->prepare($sql);
            $result = $stmt->executeQuery([
                'bean_id' => $this->id,
                'bean_module' => $module_name,
                'primary_address' => 1,
                'deleted' => 0,
            ]);

            return $result->fetchOne() ?: '';
}

public function getSerialized(bool $json = false): array|string
{
    $data = parent::getSerialized($json);
    $data['email1'] = $this->getEmail1();
    return $data;
}
    // Auto-generated SectionMethods section end
}
