<?php
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
*
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM,
 * Copyright (C) 2018-2024 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM"
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo.
 * If the display of the logos is not reasonably feasible for technical reasons, the
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

require_once('modules/DynamicFields/templates/Fields/TemplateTextArea.php');

/**
 * Studio field type for a markdown-backed text field.
 *
 * Reuses TemplateTextArea entirely (storage, admin form defaults, legacy xtpl rendering)
 * and only overrides the vardefs `type`, so that:
 * - modules with native Vue views resolve this field to the existing generic
 *   markdown.edit.vue / markdown.detail.vue components (Field.config.ts auto-discovery),
 * - modules still on legacy views keep rendering it as a plain textarea, since no
 *   SugarFieldMarkdown class exists and SugarFieldHandler falls back to SugarFieldBase.
 */
class TemplateMarkdown extends TemplateTextArea
{
    public $type = 'markdown';

    /**
     * DBManager::getFieldType() (legacy/include/database/DBManager.php) resolves the SQL
     * column type from `dbType` first, falling back to the raw `type` only when `dbType` is
     * absent. TemplateField::get_field_def() never sets `dbType`, so without this override
     * the ALTER TABLE generated by Studio would use the literal string "markdown" as the SQL
     * column type — invalid, and rejected by the database (there is no 'markdown' entry in
     * DBManager's per-driver $type_map, e.g. MysqlManager::$type_map). Force it to the same
     * 'text' column TemplateTextArea already uses, mirroring TemplateHTML::get_field_def().
     */
    public function get_field_def()
    {
        $def = parent::get_field_def();
        $def['dbType'] = 'text';

        return $def;
    }
}
